### ISSUE TITLE
Tab completion button for usernames

### ISSUE THREAD

**Issue by 3ricG** [glowing-bear/glowing-bear#878] opened 2016-12-17 15:14 UTC
Many other clients have a button/function to auto-complete names for devices that do not have a "Tab" button on their keyboard (ex: Android, iPhone, Tablets, etc.). The one main example where I think of this is the "Official" Weechat Android app:

![Image of Weechat Android](https://puu.sh/sSyKT/5044cff30e.png)

This is very convenient, and allows you to tab complete anywhere in your message. Other popular android clients like AndChat also have this functionality.

**Comment by lorenzhs** [comment] 2016-12-17 18:05
Dupe of #632, and we should have another go at this

**Closed by lorenzhs** 2016-12-17 18:05 UTC
