### ISSUE TITLE
Links containing "&sect" interpreted as HTML entity

### ISSUE THREAD

**Issue by trisk** [glowing-bear/glowing-bear#983] opened 2018-02-27 16:52 UTC
In Chrome, I've noticed that when displaying a message containing a URL like e.g.:
`https://www.facebook.com/settings?tab=facerec&section=face_recognition&view`

It gets converted to a link with the correct text, but with an href of `https://www.facebook.com/settings?tab=facerec§ion=face_recognition&amp;view`

**Comment by lorenzhs** [comment] 2018-02-27 17:09
o_O thanks for the report, I can confirm this on the latest release but it's not present any more in master (deployed at https://latest.glowing-bear.org) - looks like we should be able to fix this easily by pushing a release out of the door. I'm not sure whether it's fixed by something we changed or by an updated version of angular-sanitize, but it's fixed ;)

**Closed** 2018-02-27 17:09 UTC
