### ISSUE TITLE
The ability to use a configurable image server

### ISSUE THREAD

**Issue by DesktopMasters** [glowing-bear/glowing-bear#1200] opened 2021-10-16 01:08 UTC
I do not want to put my personal images on a server that keeps them forever or wants a login to track me,  even if I change my IP and delete my cookies.  mmm.... cookies...

For example:  I want to be able to  post an image that is unlisted without a login so I can link it one time and then have it delete its self in a week?

**Comment by Chisight** [comment] 2021-10-16 05:09
I'd be willing to help with this, but my js skills are limited.  If there is some grunt work towards getting this implemented, I'll do it.

**Comment by lorenzhs** [comment] 2021-10-18 08:44
Duplicate of #925 and #1181, see also #1050.

**Closed by lorenzhs** 2021-10-18 08:44 UTC
