### ISSUE TITLE
Add "toggle nicklist" button on main mobile view

### ISSUE THREAD

**Issue by zakius** [glowing-bear/glowing-bear#890] opened 2017-01-28 20:39 UTC
Like topic says, it seems more convenient to me to be able to just pop it to check who is on and then hide it without digging in options.    
On the other hand logout button just next to options (and/or newly added nicklist button) seems mildly dangerous, can be tapped by accident

**Comment by lorenzhs** [comment] 2017-01-30 08:42
Duplicate of #838. Pull request #849 should address this.

**Closed by lorenzhs** 2017-01-30 08:42 UTC
