### ISSUE TITLE
Add option to disable Alt-0/1/2 bindings

### ISSUE THREAD

**Issue by maurer** [glowing-bear/glowing-bear#884] opened 2017-01-10 12:40 UTC
I normally use Alt-N to select a tab in chrome, but now glowing-bear will eat these, preventing me from easily switching tabs. It would be nice if there were a spot in the options to let the shortcut go back to the browser instead.

**Comment by lorenzhs** [comment] 2017-01-10 13:15
Duplicate of #572

**Closed by lorenzhs** 2017-01-10 13:15 UTC
