### ISSUE TITLE
Change window title and possible icon when GB gets disconnected from server

### ISSUE THREAD

**Issue by Kubuxu** [glowing-bear/glowing-bear#643] opened 2015-08-13 11:31 UTC
I use glowing bear in environment with somewhat bad internet connection and I loose connection on regular basis. It would be extremely good if GB was changing window title to signal that it lost connection. It would be also nice if icon was changed in case of this event and maybe browser notification.

**Comment by lorenzhs** [comment] 2015-08-13 13:28
This is a duplicate of #539

**Closed by lorenzhs** 2015-08-13 13:28 UTC
