### ISSUE TITLE
Switching buffers won't always scroll to the bottom

### ISSUE THREAD

**Issue by JulienPalard** [glowing-bear/glowing-bear#949] opened 2017-06-13 07:36 UTC
When switching from a buffer to another, I'm sometime dropped in the middle of the conversation. Not near the "read mark", nor near the bottom.

I'm using latest.glowing.bear.org. Looks like the buffer loads some strings, then scrolls, then continue loading some strings without scrolling.

Expected behavior: Always jump at the bottom, except maybe if scroll happened manually, in which case it may have to be remembered as told in https://github.com/glowing-bear/glowing-bear/issues/407

**Comment by lorenzhs** [comment] 2017-06-13 08:04
With some probing around I can reproduce this. I guess I never noticed it because I'm usually using a portrait 1080p screen, so usually everything relevant fits onto one screen and I don't load enough lines to have scrolling. Anyone have an idea when this started happening? Could it be related to #899?

**Comment by JulienPalard** [comment] 2017-06-13 08:33
I started being aware of the issue like a week ago, but I'm not really sure. I don't often refresh my pages so it may have been here since a few days before. Not really sure...

**Comment by JulienPalard** [comment] 2017-06-19 14:30
For the record, @lorenzhs tried to fix this in https://github.com/glowing-bear/glowing-bear/pull/950.

**Comment by lorenzhs** [comment] 2017-06-19 14:31
Yeah, that didn't work so well. But since #951 is merged now this is now a duplicate of #899 / #905

**Closed by lorenzhs** 2017-06-19 14:31 UTC
Labels: bug
