### ISSUE TITLE
Sidebar font/line-height suddenly too large

### ISSUE THREAD

**Issue by gdude2002** [glowing-bear/glowing-bear#649] opened 2015-09-25 09:18 UTC
For some reason, when I logged on with Glowing Bear today, the sidebar items were suddenly twice their usual height.

![](http://i.imgur.com/1wnWA6r.png)

This looks pretty awful in my opinion, and requires me to do this so that I can see all my buffers..

![](http://i.imgur.com/uZOSJlx.png)

I'm assuming this was https://github.com/glowing-bear/glowing-bear/commit/27eb2cbc7b1ab9fb2a7e2bd15bc6d72faf15ce67 - I really can't see what this is targetting though, GB always worked fine without all the needless whitespace.

**Comment by lorenzhs** [comment] 2015-09-25 09:24
Duplicate of #646

**Closed by lorenzhs** 2015-09-25 09:24 UTC

**Comment by lorenzhs** [comment] 2015-09-25 09:26
There are user scripts that change back the behaviour, and #647 will allow you to change this back and customize glowing bear easily yourself.
